### ISSUE TITLE
Improve configurable meta tags 

### ISSUE THREAD

**Issue by tf** [codevise/pageflow#512]
#508 makes the `author`, `keyword` and `publisher` meta tags of published entries configurable in the editor. Default values can be determined via the configuration. Here are some ideas how to make the integration of the feature even more seamless.

- The default values from the configuration could be displayed as placeholders inside the editor
- There could be inline help texts explaining the new form fields
- A somewhat bigger enhancement: Default values could additionally be stored in the `Theming` model making the view helper fallback: `Entry` -> `Theming` -> `Configuration`. That way sensible defaults could be configured on an account level instead of having to be reiterated in each entry.

@tilsammans thoughts?

**Comment by tilsammans** [comment]
- [ ] display default configuration values inside the editor
- [ ] inline help explaining the new form fields
- [ ] store default values in the `Theming` model

I need help with just the last one: will that mean adding stuff into `/admin/accounts/nnn/edit`? There is a redirect_url there already, for my purposes that one is totally fine to use as the default. I can image it would be for 90% of cases (which makes it a nice default).

**Comment by tilsammans** [comment]
Please disregard my comment about the redirect_url. I was thinking of something else.

**Comment by tf** [comment]
Great that you can work on this! Yes, we need to add fields to the [account edit form](https://github.com/codevise/pageflow/blob/master/app/views/admin/accounts/_form.html.erb#L20) for the three new meta tag attributes on `Theming` and white list them as [permitted attributes](https://github.com/codevise/pageflow/blob/master/admins/pageflow/accounts.rb#L82).

Adding the attributes to the [theming seed data](https://github.com/codevise/pageflow/blob/master/app/views/pageflow/editor/themings/_theming.json.jbuilder) makes them [available as `pageflow.theming`](https://github.com/codevise/pageflow/blob/master/app/assets/javascripts/pageflow/editor/initializers/setup_collections.js#L12) inside the editor. Probably that's also an okay place to fallback to the default values from the configuration if the theming does not provide a certain attribute. That way inside the editor placeholders can always be taken from `pageflow.theming`.

**Comment by tilsammans** [comment]
I can work on these in May at the earliest; but would still like to do them. They will be a separate PR per improvement.

**Comment by tilsammans** [comment]
@tf need your help on the `pageflow.TextInputView` backbone model. I can [list the defaults on a new entry editor as placeholders](https://github.com/scrollytelling/pageflow/commit/9e7e7698a204eb18a1f87339bc876fef2a79bdb2), but how should I put them as default _values_ for those fields? Obviously I don't wish to override values already present, just suggest them in case the value is blank. I am not familiar with backbone how to do this.

**Comment by tf** [comment]
Isn't displaying the default values as placeholder sufficient? Backbone default values end up getting persisted to the DB in most cases. That's not we want here, though, since changing the default meta tags should probably take effect in all entries that do not have custom meta tags, right?

**Comment by tilsammans** [comment]
That's up for debate, actually.

My idea with the theming defaults was that these would actually be copied over to the revision, and would persist there, separately. This way they would become stored with the revision and would be frozen in time. Much like you would otherwise publish an entry.

If we're not doing that, changing the defaults on theming will retroactively change the metas on published entries, as soon as cache is expired. I assumed you would want to store these defaults with the revision instead?

**Comment by tf** [comment]
You are right. This is also better aligned with the way default widget types on the theming work. Those [get copied over on entry creation](https://github.com/codevise/pageflow/blob/master/app/models/pageflow/entry.rb#L45). That would probably be the place to also handle meta tag values.

And what about the global defaults? Do they also get copied on theming creation? Or are they still fallback values in the sense of the current implementation?

**Comment by tilsammans** [comment]
> And what about the global defaults?

I can be convinced either way. Something can be said for copying them over as well. That way the metas really become part of the revision and stay with it during its lifetime.

It will be a bit more work though and it deviates from the original implementation as simple fallbacks.

I will assume we will want to copy them over, so that means tweaking the original implementation. I will first complete this Theming work and give the fallbacks a little more thought.

**Comment by tf** [comment]
+1 for copying. One could have used a default in the migration. But now
that the config option is there, I guess we can simply also use it in the
migration to stay consistent.

Joost Baaij <notifications@github.com> schrieb am Fr., 17. Juni 2016, 16:49:

**Comment by tilsammans** [comment]
I've created #538 to contain this work. Can you have a look?

Do we need to do anything for the "copy story" scenario? And should we now ditch the [fallbacks in the meta helper](https://github.com/codevise/pageflow/blob/083fd94de5bea9e7a88ff8180e5738fada89e559/app/helpers/pageflow/meta_tags_helper.rb#L5)?

**Comment by tf** [comment]
:tada:
