### ISSUE TITLE
Migrate to ActiveJob

### ISSUE THREAD

**Issue by tf** [codevise/pageflow#940]
Steps required to decouple Pageflow from Resque and make better use of existing Rails features:

- [x] Migrate `state_machine_job` gem to ActiveJob (https://github.com/codevise/state_machine_job/pull/9)

- [ ] Rewrite jobs to use ActiveJob base class (#976)

- [ ] Rewrite `pageflow-chart` jobs to use Active Job.

- [ ] Rewrite `pageflow-panorama` jobs to use Active Job.

- [x] Remove `devise-async` (#932)
 No longer needed.

- [ ] Drop `resque`/`resque-logger` dependency (#976)
Active Job defaults to tagged log entries inside normal Rails log. Seems fine with me. 

- [x] Find out how to handle `resque-scheduler` (#976)
 [It looks like](https://github.com/rails/rails/blob/master/activejob/lib/active_job/queue_adapters/resque_adapter.rb#L37) ActiveJob's resque adapter knows how to integrate with `resque-scheduler`.

- [ ] Adapt install generator to setup `resque` as default backend for ActiveJob (#976)
